### ISSUE TITLE
Picking up the ControlNet models from other SD webui installations

### ISSUE THREAD

**Issue by yhdanid** [Fannovel16/comfy_controlnet_preprocessors#73]
I didn't know where to post this. If it's not an issue, please accept my apologies. 

I already have AUTOMATIC1111 webui installed together with the ControlNet extension. I have followed the Readme instructions at ComfyUI github page regarding editing the extra_model_paths.yaml to make it point at my webui installation to pick up the models from there.

I wonder if ComfyUI is also able to pick up the ControlNet models from its AUTO1111 extensions directory as well. If not, is there a way (like the one for the checkpoints/models used above) for pointing ComfyUI at the models used by the extensions too?

Thanks.

**Comment by jjangga0214** [comment]
Hi. 

Preprocessor models and Controlnet models are different.

For example, the openpose preprocessor extracts a human skeleton from your image.
(input: image, output: skeleton)

On the other hand, the openpose ControlNet model lets Stable Diffusion draw a picture of a person whose pose is similar to the skeleton pose.
(input: skeleton, output: image)

The official ComfyUI repo provides nodes for ControlNet, but not for Preprocessors.
This repo([comfy_controlnet_preprocessors](https://github.com/Fannovel16/comfy_controlnet_preprocessors)) is for preprocessor.

> if ComfyUI is also able to pick up the ControlNet models from its AUTO1111 extensions

This repo does only care about preprocessor, not ControlNet models. That's what ComfyUI should care.

> extra_model_paths.yaml to make it point at my webui installation 

You can configure `extra_model_paths.yaml` for ControlNet as well.

```yaml
# Other contents are omitted for brevity.
a111:
    base_path: /path/to/stable-diffusion-webui/
    # It's recommended(new way) to place ControlNet models in /path/to/stable-diffusion-webui/models/ControlNet . 
    # But if you want to place them in (old way) /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models
    controlnet: extensions/sd-webui-controlnet/models
```
